language: csharp
sudo: false
dist: trusty
mono: none
dotnet: 2.0.0
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1   
os:
  - linux
#  - osx
# osx_image: xcode8.3
script:
  - cd cloudscribe-core-ef
  - if test "$TRAVIS_OS_NAME" == "linux"; then dotnet restore; fi
  - if test "$TRAVIS_OS_NAME" == "osx"; then dotnet restore --disable-parallel; fi
  - dotnet build -c Release
  - cd ../cloudscribe-core-ef-mysql
  - if test "$TRAVIS_OS_NAME" == "linux"; then dotnet restore; fi
  - if test "$TRAVIS_OS_NAME" == "osx"; then dotnet restore --disable-parallel; fi
  - dotnet build -c Release
  - cd ../cloudscribe-core-ef-pgsql
  - if test "$TRAVIS_OS_NAME" == "linux"; then dotnet restore; fi
  - if test "$TRAVIS_OS_NAME" == "osx"; then dotnet restore --disable-parallel; fi
  - dotnet build -c Release
  - cd ../cloudscribe-core-nodb
  - if test "$TRAVIS_OS_NAME" == "linux"; then dotnet restore; fi
  - if test "$TRAVIS_OS_NAME" == "osx"; then dotnet restore --disable-parallel; fi
  - dotnet build -c Release
  - cd ../cloudscribe-idserver-ef
  - if test "$TRAVIS_OS_NAME" == "linux"; then dotnet restore; fi
  - if test "$TRAVIS_OS_NAME" == "osx"; then dotnet restore --disable-parallel; fi
  - dotnet build -c Release
  - cd ../cloudscribe-idserver-ef-mysql
  - if test "$TRAVIS_OS_NAME" == "linux"; then dotnet restore; fi
  - if test "$TRAVIS_OS_NAME" == "osx"; then dotnet restore --disable-parallel; fi
  - dotnet build -c Release
  - cd ../cloudscribe-idserver-ef-pgsql
  - if test "$TRAVIS_OS_NAME" == "linux"; then dotnet restore; fi
  - if test "$TRAVIS_OS_NAME" == "osx"; then dotnet restore --disable-parallel; fi
  - dotnet build -c Release
  - cd ../cloudscribe-idserver-nodb
  - if test "$TRAVIS_OS_NAME" == "linux"; then dotnet restore; fi
  - if test "$TRAVIS_OS_NAME" == "osx"; then dotnet restore --disable-parallel; fi
  - dotnet build -c Release
  - cd ../SimpleContent-cloudscribecore-ef
  - if test "$TRAVIS_OS_NAME" == "linux"; then dotnet restore; fi
  - if test "$TRAVIS_OS_NAME" == "osx"; then dotnet restore --disable-parallel; fi
  - dotnet build -c Release
  - cd ../SimpleContent-cloudscribecore-ef-mysql
  - if test "$TRAVIS_OS_NAME" == "linux"; then dotnet restore; fi
  - if test "$TRAVIS_OS_NAME" == "osx"; then dotnet restore --disable-parallel; fi
  - dotnet build -c Release
  - cd ../SimpleContent-cloudscribecore-ef-pgsql
  - if test "$TRAVIS_OS_NAME" == "linux"; then dotnet restore; fi
  - if test "$TRAVIS_OS_NAME" == "osx"; then dotnet restore --disable-parallel; fi
  - dotnet build -c Release
  - cd ../SimpleContent-cloudscribecore-nodb
  - if test "$TRAVIS_OS_NAME" == "linux"; then dotnet restore; fi
  - if test "$TRAVIS_OS_NAME" == "osx"; then dotnet restore --disable-parallel; fi
  - dotnet build -c Release
  - cd ../SimpleContent-SimpleAuth-nodb
  - if test "$TRAVIS_OS_NAME" == "linux"; then dotnet restore; fi
  - if test "$TRAVIS_OS_NAME" == "osx"; then dotnet restore --disable-parallel; fi
  - dotnet build -c Release
  - cd ../SimpleContent-SimpleAuth-nodb-multitenant
  - if test "$TRAVIS_OS_NAME" == "linux"; then dotnet restore; fi
  - if test "$TRAVIS_OS_NAME" == "osx"; then dotnet restore --disable-parallel; fi
  - dotnet build -c Release
